name: paraclu_paraclu
description: Paraclu finds clusters in data attached to sequences.
keywords:
  - Paralclu
  - crosslinks
  - k-mer
  - bed
tools:
  - paraclu:
      description: Paraclu finds clusters in data attached to sequences.
      homepage: https://gitlab.com/mcfrith/paraclu
      documentation: None
      tool_dev_url: None

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bed:
      type: file
      description: BED file of crosslinks
      pattern: "*.{bed,bed.gz}"
  - min_value:
      type: integer
      description: Parclu minimum threshold value

output:
  - tsv:
      type: file
      description: Output TSV of significant signals
      pattern: "*.tsv"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@codeprimate123"
  - "@kkuret"
  - "@chris-cheshire"
