name: dump_software_versions
description: Custom module used to dump software versions
keywords:
  - version
input:
  - versions:
      type: file
      description: YML file containing software versions
      pattern: "*.yml"
output:
  - yml:
      type: file
      description: Standard YML file containing software versions
      pattern: "software_versions.yml"
  - mqc_yml:
      type: file
      description: MultiQC custom content YML file containing software versions
      pattern: "software_versions_mqc.yml"
  - mqc_unique_yml:
      type: file
      description: MultiQC custom content YML file containing unique software versions
      pattern: "software_versions_mqc.yml"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@chris-cheshire"
