name: samplesheet_to_barcode
description: |
  Converts CSV describing samples and creates a barcodes spreadsheet that can be
  read by Ultraplex.
tools:
  - pandas:
      description: |
        Flexible and powerful data analysis / manipulation library for Python,
        providing labeled data structures similar to R data.frame objects,
        statistical functions, and much more.
      homepage: https://pandas.pydata.org/
      documentation: https://pandas.pydata.org/docs/
      licence: ["BSD-3"]
input:
  - annotation:
      type: file
      description: A samples CSV annotation file.
output:
  - barcodes:
      type: file
      description: Barcodes file.
      pattern: "barcodes.csv"
  - samplesheet:
      type: file
      description: Merged samplesheet file of columns relevant to Ultraplex.
      pattern: "samplesheet.csv"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@CharlotteAnne"
  - "@alexharston"
  - "@samirelanduk"
  - "@chris-cheshire"
