name: linting
# This workflow is triggered on PRs to dev or master
# It runs linting tools for nextflow, python and markdown/yaml/json

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  EditorConfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - name: Install editorconfig-checker
        run: npm install -g editorconfig-checker

      - name: Run ECLint check
        run: editorconfig-checker -exclude README.md $(find .* -type f | grep -v '.git\|.py\|.md\|json\|yml\|yaml\|html\|css\|work\|.nextflow\|log.txt\|Makefile')

  Prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - name: Install Prettier
        run: npm install -g prettier

      - name: Run Prettier --check
        run: prettier --check ${GITHUB_WORKSPACE}

  ## Python linting (`black`) is failing
  # To fix this CI test, please run:
  # * Install [`black`](https://black.readthedocs.io/en/stable/): `pip install black`
  # * Fix formatting errors in your pipeline: `black .`
  PythonBlack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check code lints with Black
        uses: psf/black@stable
